### ISSUE TITLE
什么时候能更新一版期待

### ISSUE THREAD

**Issue by uguopai** [sphinx-quant/sphinx-quant#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by qzm** [comment]
您好，这边会加快项目进度

**Comment by uguopai** [comment]
能否加入该项目的开发？

**Comment by uguopai** [comment]
？？？？？

**Comment by qzm** [comment]
> 能否加入该项目的开发？

如果有兴趣的话，欢迎给项目提PR

**Comment by uguopai** [comment]
现在开发到什么进度了？不是说6月份放出来一版可以下载的么？
