### ISSUE TITLE
完善一下文档

### ISSUE THREAD

**Issue by AllenFong** [sphinx-quant/sphinx-quant#9]
你好，想运行一下代码，能完善一下安装运行文档吗？

**Comment by qzm** [comment]
你好，现在还处于开发中，并不能真正的用起来，请持续关注，预计6月份，发布一个正式的可运行的Alpha版本，届时将提供一键安装脚本，并且提供相应的文档

**Comment by AllenFong** [comment]
好的，非常期待

**Comment by uguopai** [comment]
都快7月了 还没更新一版么
